# Generated by Django 5.0.2 on 2024-03-04 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='password',
        ),
        migrations.AlterField(
            model_name='logs',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
        ),
        migrations.AlterField(
            model_name='server',
            name='users',
            field=models.ManyToManyField(to='users.userprofile'),
        ),
        migrations.AlterField(
            model_name='technician',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
        ),
    ]
