# Generated by Django 5.0.2 on 2024-03-04 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_server_password_alter_logs_created_by_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Logs',
            new_name='Log',
        ),
    ]
