# Generated by Django 5.0.2 on 2024-03-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_log_created_by_alter_server_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technician',
            name='issues_resolved',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='technician',
            name='server',
            field=models.ManyToManyField(blank=True, null=True, to='core.server'),
        ),
    ]
