# Generated by Django 5.0.2 on 2024-03-05 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_technician_issues_resolved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='technician',
        ),
        migrations.DeleteModel(
            name='Technician',
        ),
    ]
