# Generated by Django 5.0.2 on 2024-03-05 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_log'),
        ('users', '0002_remove_userprofile_roles_userprofile_is_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technician',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
        ),
    ]
