# Generated by Django 5.0.2 on 2024-03-05 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_technician_user'),
        ('users', '0002_remove_userprofile_roles_userprofile_is_admin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technician',
            old_name='user',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='log',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
        ),
        migrations.AlterField(
            model_name='log',
            name='technician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.technician'),
        ),
        migrations.AlterField(
            model_name='server',
            name='users',
            field=models.ManyToManyField(to='users.userprofile'),
        ),
    ]
