# Generated by Django 5.0.2 on 2024-03-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_user_technician_name_alter_log_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technician',
            name='issues_resolved',
            field=models.IntegerField(default=0),
        ),
    ]
