# Generated by Django 5.0.2 on 2024-03-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_technician_issues_resolved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='stotage',
            new_name='storage',
        ),
        migrations.RemoveField(
            model_name='server',
            name='port',
        ),
        migrations.AddField(
            model_name='server',
            name='allow_ssh_trafic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='server',
            name='application_image',
            field=models.CharField(default='Ubuntu', max_length=100),
        ),
        migrations.AddField(
            model_name='server',
            name='network',
            field=models.CharField(default='VPC-aaabbbcc', max_length=100),
        ),
    ]
