# Generated by Django 5.0.2 on 2024-03-07 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_stotage_server_storage_remove_server_port_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='instance_state',
            field=models.CharField(default='Running', max_length=100),
        ),
    ]
