# Generated by Django 5.0.2 on 2024-03-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_server_instance_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved')], default='Open', max_length=20),
        ),
        migrations.AddField(
            model_name='technician',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
