# Generated by Django 5.0.2 on 2024-03-08 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_log_status_technician_is_active'),
        ('users', '0002_remove_userprofile_roles_userprofile_is_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modified_logs', to='users.userprofile'),
        ),
        migrations.AlterField(
            model_name='log',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_logs', to='users.userprofile'),
        ),
    ]
